### ISSUE TITLE
Private registry with auth (CA cert)

### ISSUE THREAD

**Issue by willowandcreek** [rancherio/rancher#1059]
Hi,

I am having issues trying to get rancher to authenticate against a private registry sitting behind an nginx proxy secured using SSL cert from GoDaddy. I am running 1 management node and 2 hosts. On the management node I used: ```docker run -d --restart=always -p 8080:8080 rancher/server``` and on the hosts I used: ```docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.8 http://192.168.10.200:8080/v1/scripts/HASH```

All works well and I can see the hosts on the management UI. However when I try to create a service using a simple test image that I have stored on my private registry I get an error saying unable to pull since authentication required. Here is the logs from the agent:

```
2015-06-05T03:59:44.476416904Z 2015-06-05 03:59:44,469 ERROR agent [140632932200112] [event.py:108] e76104e4-c7f9-4bfd-8e9e-ae80a5811574 : Unknown error
2015-06-05T03:59:44.476416904Z Traceback (most recent call last):
2015-06-05T03:59:44.476416904Z   File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 91, in _worker_main
2015-06-05T03:59:44.476416904Z     resp = agent.execute(req)
2015-06-05T03:59:44.476416904Z   File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
2015-06-05T03:59:44.476416904Z     return self._router.route(req)
2015-06-05T03:59:44.476416904Z   File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
2015-06-05T03:59:44.476416904Z     resp = handler.execute(req)
2015-06-05T03:59:44.476416904Z   File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 33, in execute
2015-06-05T03:59:44.476416904Z     return method(req=req, **req.data.__dict__)
2015-06-05T03:59:44.476416904Z   File "/var/lib/cattle/pyagent/cattle/storage/__init__.py", line 27, in image_activate
2015-06-05T03:59:44.476416904Z     action=lambda: self._do_image_activate(image, storage_pool,
2015-06-05T03:59:44.476416904Z   File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 71, in _do
2015-06-05T03:59:44.476416904Z     action()
2015-06-05T03:59:44.476416904Z   File "/var/lib/cattle/pyagent/cattle/storage/__init__.py", line 28, in <lambda>
2015-06-05T03:59:44.476416904Z     progress)
2015-06-05T03:59:44.476416904Z   File "/var/lib/cattle/pyagent/cattle/plugins/docker/storage.py", line 98, in _do_image_activate
2015-06-05T03:59:44.476416904Z     message))
2015-06-05T03:59:44.476416904Z ImageValidationError: Image [PRIVATE_REGISTRY/testapps-web-1:0.0.2] failed to pull : Authentication is required.
```

Note: PRIVATE_REGISTRY is the CNAME of my private registry. I have also added the private registry on the Rancher UI. The SSL cert is a proper wildcard cert issed by GoDaddy and works fine when doing 'docker login'. Is this something related to https://github.com/rancherio/rancher/issues/1020 ?

**Comment by will-chan** [comment]
We are working on this right now and is related to #1020 .

**Comment by sangeethah** [comment]
Private registry works with server version - v0.23.0-rc6

You should be able to launch containers using private registries by following these steps: 
1.If you are working with self signed certs :
Following commands need to be run on each of the hosts where you expect the containers to be started:
DOMAIN and PORT are the domain and port where the private registry is hosted

openssl s_client -showcerts -connect ${DOMAIN}:${PORT} /dev/null|openssl x509 -outform PEM >ca.crt
sudo cp ca.crt /etc/docker/certs.d/${DOMAIN}/ca.crt
cat ca.crt | sudo tee -a /etc/ssl/certs/ca-certificates.crt
sudo service docker restart

on the rancher server , add a registry for your private registry.
Add a container using an image from your private registry. Containers will start successfully.

2.If you are using private registries with no authentication :
Add --insecure-registry ${DOMAIN}:${PORT} to the docker daemon flags and restart docker.

Add a container using an image from your private registry. Containers will start successfully.

Note - when restarting docker on the host , you may encounter issues with network Agent being stuck in “starting” state because of #931. To workaround the issue , reboot the host.

**Comment by willowandcreek** [comment]
Thanks for the fix and update. I have verified that private registries are working fine with v0.23.0-rc6. My setup is a registry secured behind nginx with authentication over a GoDaddy issued SSL certificate. Works like a charm now.

**Comment by mtrofimm** [comment]
@willowandcreek are you using private registry with rancher? If so, which version?
I still have auth problem. See: #3634 and #3008.

**Comment by willowandcreek** [comment]
Yep. Using private registry with any issue for awhile now. However my registry uses a proper SSL cert. Not a self signed one. I am not sure of the behavior if you use a self signed one.

**Comment by willowandcreek** [comment]
Just a side note - when I filed this issue I was on registry 1.x behind a nginx rev proxy. Lately I have switched to using the registry 2.x image directly. The only change I did was put in a ldap auth layer to secure my registry. But yes working fine without any issues.

**Comment by mtrofimm** [comment]
Thanks for information. 
My registry also uses a proper ssl cert (from letsencrypt) - I checked it from bare docker commad: login and pull works OK. 
Can you share your rancher docker versions?

**Comment by willowandcreek** [comment]
Gotta get back to you tomorrow when I am back at work. Instances are IP locked haha.

**Comment by mtrofimm** [comment]
Sure :) 
Maybe if you have a moment tomorrow you can look at my testing ranchner server?

**Comment by willowandcreek** [comment]
Here's my versions:

Rancher	v0.56.1
Cattle	v0.141.1
User Interface	v0.86.0
Rancher Compose	v0.7.1

Feel free to message me if you need any help. I am not a pro at rancher, but I can try to help out as much as possible. Everyone should get rancher working really, coz its such an awesome tool and shouldn't be missed out on during an evaluation! Haha

Cheers
