### ISSUE TITLE
Unable to use Links/Private Network when containers are on different servers

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#110]
![screen shot 2015-02-22 at 2 17 10 pm](https://cloud.githubusercontent.com/assets/204682/6319914/8365354e-ba9d-11e4-9496-1a55fd95aa38.png)

I launched a Rancher Server and an Agent on AWS ec2 instances with all ports open for all network protocols. I launched a memcached container on one of the servers. I explicitly exported the memcached port (11211) as well as declared it as exposed in the dockerfile. On a second server I launched a ubuntu container and linked my memcached container. I can see that the containers are linked as when I run ```env``` in the ubuntu container I see:

 	env | grep PORT
	MEMCACHED_PORT_11211_TCP_PORT=25098
	MEMCACHED_PORT_11211_TCP_PROTO=tcp
	MEMCACHED_PORT=tcp://10.42.185.20:25098
	MEMCACHED_PORT_11211_TCP_ADDR=10.42.185.20
	MEMCACHED_PORT_11211_TCP=tcp://10.42.185.20:25098

However when I try to run any of the following I get a time out.

    # Docker Linked Host and Port
    telnet 10.42.185.20 25098
    
    # Docker Linked Host and Exposed Port
    telnet 10.42.185.20 11211
   
    #Rancher VPC Host and Exposed Port
    telnet 10.42.194.251 1211

    #Rancher VPC Host and Linked Port Port
    telnet 10.42.194.251 25098

However, when I use the actual port of the machine I am able to communicate. 

    telnet 172.30.0.128 11211
    Trying 172.30.0.128...
    Connected to 172.30.0.128.
    Escape character is '^]'.

The logs from my containers are here are linked below with some relevant parts highlighted inline. let me know what I should do to investigate more.

* [rancher/agent-instance:v0.1.0  on Memcached node ](https://gist.github.com/usmanismail/6ecb6b168d652de4e66c#file[]()-gistfile1-txt)

Errors:

    INFO: Running /var/lib/cattle/download/hosts/hosts-1-6bec032bb6b0d2490d529c93161cbbd6256f532de1a638615d6ea61ba6c94237/apply.sh
    tar: ./etc/hosts: Cannot open: File exists
    tar: Exiting with failure status due to previous errors 
    ....
    INFO: ROOT -> ./etc/racoon/racoon.conf
    racoon - IKE keying daemon will not be started as /proc/net/pfkey is not
    available or a suitable 2.6 (or 2.4 with IPSEC backport)
    kernel with af_key.[k]o module installed. 

* [rancher/agent:v0.3.2 on Memcached node ](https://gist.github.com/usmanismail/b04f8a460a13150fa169#file-gistfile1-txt)

Error:

    2015-02-22 18:01:04,658 ERROR agent [140435930755952] [event.py:108] 213b7c34-1c11-438e-9cf2-a8a0f6b62fad : Unknown error
	Traceback (most recent call last):
	File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 91, in _worker_main
	resp = agent.execute(req)
	File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
	return self._router.route(req)
	File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
	resp = handler.execute(req)
	File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 33, in execute
	return method(req=req, **req.data.__dict__)
	File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 145, in delegate_request
	event)
	File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 87, in container_exec
	}, timeout=DockerConfig.delegate_timeout())
	File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 500, in post
	return self.request('POST', url, data=data, json=json, **kwargs)
	File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 457, in request
	resp = self.send(prep, **send_kwargs)
	File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 569, in send
	r = adapter.send(request, **kwargs)
	File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 407, in send
	raise ConnectionError(err, request=request)
	ConnectionError: ('Connection aborted.', error(111, 'ECONNREFUSED')) 

* [rancher/server:latest logs](https://gist.github.com/usmanismail/15b5ab7b356eb4ed7856#file-gistfile1-txt)

* [rancher/agent-instance:v0.1.0 on ubuntu node ](https://gist.github.com/usmanismail/1056fdd52e6d68f3a97f#file-gistfile1-txt)

* [rancher/agent:v0.3.2 on ubuntu node](https://gist.github.com/usmanismail/0d2ae782c4d9e59c9cdd#file-gistfile1-txt)

Error:

     c93bcc339c5cb2de9acfc2569dd229cdad94ad61729b032eaed280e2674912c7"
    2015-02-22 17:59:39,745 ERROR agent [139800033118480] [event.py:108] e0c7767c-d227-430a-a3f9-89169e475579 : Unknown error
    Traceback (most recent call last):
      File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 91, in _worker_main
        resp = agent.execute(req)
      File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
        return self._router.route(req)
      File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
        resp = handler.execute(req)
      File "/var/lib/cattle/pyagent/cattle/agent/handler.py", line 33, in execute
        return method(req=req, **req.data.__dict__)
      File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 145, in delegate_request
        event)
      File "/var/lib/cattle/pyagent/cattle/plugins/docker/delegate.py", line 87, in container_exec
        }, timeout=DockerConfig.delegate_timeout())
      File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 500, in post
        return self.request('POST', url, data=data, json=json, **kwargs)
      File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 457, in request
        resp = self.send(prep, **send_kwargs)
      File "/var/lib/cattle/pyagent/dist/requests/sessions.py", line 569, in send
        r = adapter.send(request, **kwargs)
      File "/var/lib/cattle/pyagent/dist/requests/adapters.py", line 407, in send
        raise ConnectionError(err, request=request)
    ConnectionError: ('Connection aborted.', error(111, 'ECONNREFUSED'))
    I0222 17:59:45.978196 00693 manager.go:395] Added container: "/docker/8001e899efb82987b71c39ec0f80ac1558991f4e5bef0654bd94cf541c2464bf" (aliases: [b0cb4e29-1171-4ce8-8ab9-e81e5f12ae0f 8001e899efb82987b71c39ec0f80ac1558991f4e5bef0654bd94cf541c2464bf], namespace: "docker")
    I0222 17:59:45.978281 00693 container.go:154] Start housekeeping for container "/docker/8001e899efb82987b71c39ec0f80ac1558991f4e5bef0654bd94cf541c2464bf"

**Comment by usmanismail** [comment]
See issue #112 for details.
