### ISSUE TITLE
Errors seen in network agent .

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#1210]
Server version - V0.24.0-rc3

I see this error when Rancher agent is started in a host that is behing proxy.

          ^
Error: Cannot find module '/var/lib/cattle/console-agent/agent.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

module.js:340
    throw err;
          ^
Error: Cannot find module '/var/lib/cattle/console-agent/agent.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
2015-06-13 16:30:38,363 ERROR docker [140262621033328] [delegate.py:126] Can not call [80c7dd7a-4c7e-4b47-ab0e-9c4121b2d67b], container is not running 
time="2015-06-13T16:30:38Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"af91628d54738b0c75ef1ee07a0c11f6cf640913e5320bb0c8a415499538f834\", From:\"rancher/agent-instance:v0.3.1\", Time:1434213038}" 
time="2015-06-13T16:30:38Z" level="info" msg="Assigning IP [10.42.36.60/16], ContainerId [af91628d54738b0c75ef1ee07a0c11f6cf640913e5320bb0c8a415499538f834], Pid [8331]" 
time="2015-06-13T16:30:38Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"af91628d54738b0c75ef1ee07a0c11f6cf640913e5320bb0c8a415499538f834\", From:\"-simulated-\", Time:0}" 
time="2015-06-13T16:30:38Z" level="info" msg="Container locked. Can't run StartHandler. ID: [af91628d54738b0c75ef1ee07a0c11f6cf640913e5320bb0c8a415499538f834]" 

module.js:340
    throw err;
          ^
Error: Cannot find module '/var/lib/cattle/console-agent/agent.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

module.js:340
    throw err;
          ^
Error: Cannot find module '/var/lib/cattle/console-agent/agent.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by sangeethah** [comment]
Tested with Server version - V0.24.0-rc4

I dont see the errors mentioned in this issue when Rancher agent is started in a host that is behind proxy.
