### ISSUE TITLE
A docker image name starting with space ' ' will lead to stacktrace and no UI response

### ISSUE THREAD

**Issue by feliksik** [rancherio/rancher#25]
rancher/server image id 26345bd126dd; 

Seen behavior: if I use image name ' google/cadvisor:latest' (I copied two spaces) when adding an image, clicking "Deploy" doesn't do anything. The rancher/server logs showed a stacktrace. Problem resolved by removing spaces.
Expected behavior: resilience (strip()), or a notification of the error. 

```
2014-12-17 16:59:50,420 ERROR [:] [] [] [] [qtp430484574-54] [i.g.i.g.r.handler.ExceptionHandler  ] Exception in 
API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@39e2bcc3] java.lang.IllegalArgumentException: Illegal character in path at index 40: https://index.docker.io/v1/repositories/  google/cadvisor/images
        at java.net.URI.create(URI.java:859) ~[na:1.7.0_65]
        at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69) ~[httpclient-4.3.1.jar:4.3.1]
        at org.apache.http.client.fluent.Request.Get(Request.java:80) ~[fluent-hc-4.3.1.jar:4.3.1]
        at io.cattle.platform.docker.client.DockerClient.lookup(DockerClient.java:43) ~[cattle-docker-storage-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.docker.storage.DockerStoragePoolDriver.populateExtenalImageInternal(DockerStoragePoolDriver.java:46) ~[cattle-docker-storage-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.storage.pool.AbstractKindBasedStoragePoolDriver.populateExtenalImage(AbstractKindBasedStoragePoolDriver.java:31) ~[cattle-iaas-storage-service-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.storage.service.impl.StorageServiceImpl.populateNewRecord(StorageServiceImpl.java:51) ~[cattle-iaas-storage-service-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.storage.service.impl.StorageServiceImpl.registerRemoteImage(StorageServiceImpl.java:38) ~[cattle-iaas-storage-service-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.storage.api.filter.ExternalTemplateInstanceFilter.validateImageUuid(ExternalTemplateInstanceFilter.java:56) ~[cattle-iaas-storage-service-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.storage.api.filter.ExternalTemplateInstanceFilter.create(ExternalTemplateInstanceFilter.java:42) ~[cattle-iaas-storage-service-0.5.0-SNAPSHOT.jar:na]
        at io.github.ibuildthecloud.gdapi.request.resource.impl.FilteredResourceManager.create(FilteredResourceManager.java:56) ~[gdapi-java-server-0.4.2.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:39) ~[gdapi-java-server-0.4.2.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[gdapi-java-server-0.4.2.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) ~[gdapi-java-server-0.4.2.jar:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.write(DefaultReadWriteApiDelegate.java:22) ~[gdapi-java-server-0.4.2.jar:na]
        at sun.reflect.GeneratedMethodAccessor570.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_65]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94) ~[spring-tx-3.2.4.RELEASE.jar:3.2.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
        at com.sun.proxy.$Proxy35.write(Unknown Source) ~[na:na]
        at io.github.ibuildthecloud.gdapi.request.handler.write.ReadWriteApiHandler.handle(ReadWriteApiHandler.java:19) ~[gdapi-java-server-0.4.2.jar:na]
        at io.github.ibuildthecloud.gdapi.servlet.ApiRequestFilterDelegate.doFilter(ApiRequestFilterDelegate.java:88) ~[gdapi-java-server-0.4.2.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter$1.runInContext(ApiRequestFilter.java:61) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:104) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.api.servlet.ApiRequestFilter.doFilter(ApiRequestFilter.java:54) [cattle-framework-api-0.5.0-SNAPSHOT.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82) [jetty-servlets-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:256) [jetty-servlets-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) [jetty-security-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.11
.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075) [jetty-server-8.1.1
1.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384) [jetty-servlet-8.1.11.v20130
520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.11.
v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009) [jetty-server-8.1.11
.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.11.v20
130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.11.v
20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.11.v20130520.jar:8.1.11.v201
30520]
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) [jetty-
server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960) [jetty-server
-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:102
1) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.11.v20130520.jar:8.1.
11.v20130520]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.11.v20130520.jar
:8.1.11.v20130520]
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.11.
v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) [jetty-io-8.1.11
.v20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-8.1.11.v
20130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.11.v2
0130520.jar:8.1.11.v20130520]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.11.v20
130520.jar:8.1.11.v20130520]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]
Caused by: java.net.URISyntaxException: Illegal character in path at index 40: https://index.docker.io/v1/reposit
ories/  google/cadvisor/images
        at java.net.URI$Parser.fail(URI.java:2829) ~[na:1.7.0_65]
        at java.net.URI$Parser.checkChars(URI.java:3002) ~[na:1.7.0_65]
        at java.net.URI$Parser.parseHierarchical(URI.java:3086) ~[na:1.7.0_65]
        at java.net.URI$Parser.parse(URI.java:3034) ~[na:1.7.0_65]
        at java.net.URI.<init>(URI.java:595) ~[na:1.7.0_65]
        at java.net.URI.create(URI.java:857) ~[na:1.7.0_65]
        ... 63 common frames omitted
```

**Comment by cjellick** [comment]
@hibooboo2 You might want to consider this issue as you work on the private repo feature.

**Comment by deniseschannon** [comment]
This should be fixed with this issue: https://github.com/rancherio/rancher/issues/239

**Comment by vincent99** [comment]
This should be properly trimmed now..

**Comment by tfiduccia** [comment]
v0.17.0
Verified fixed
