### ISSUE TITLE
Failed to load UI from [http://releases.rancher.com/ui/0.13.1/static/index.html] java.net.ConnectException: Connection timed out

### ISSUE THREAD

**Issue by gghonor** [rancherio/rancher#390]
I can't startup normally.
I got this log..
Do I have to any proxy setting in rancher/server container?
I've done proxy setting in my ubuntu already.
"docker pull rancher/server" is no problem.

2015-04-01 04:46:26,614 INFO    [main] [ConsoleStatus] [104/104] [56791ms] [0ms] Starting storage-simulator 
2015-04-01 04:48:34,602 ERROR [:] [] [] [] [main           ] [i.c.p.i.a.s.filter.UIPathFilter     ] Failed to load UI from [http://releases.rancher.com/ui/0.13.1/static/index.html] java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_75]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_75]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_75]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_75]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_75]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_75]
	at java.net.Socket.connect(Socket.java:528) ~[na:1.7.0_75]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.7.0_75]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.7.0_75]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.7.0_75]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.7.0_75]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.7.0_75]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997) ~[na:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933) ~[na:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851) ~[na:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301) ~[na:1.7.0_75]
	at io.cattle.platform.iaas.api.servlet.filter.UIPathFilter.reloadIndex(UIPathFilter.java:57) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.servlet.filter.UIPathFilter.init(UIPathFilter.java:35) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:119) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:719) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1252) [jetty-webapp-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:710) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494) [jetty-webapp-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.Server.doStart(Server.java:282) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at io.cattle.platform.launcher.jetty.Main.main(Main.java:125) [0.5.0-SNAPSHOT-44a2a02fbe642620033e4cef2c51554f8e11082e-11f11708-0347-43b4-920b-5f4e81f00907/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at io.cattle.platform.launcher.Main.run(Main.java:188) [0.5.0-SNAPSHOT-44a2a02fbe642620033e4cef2c51554f8e11082e-11f11708-0347-43b4-920b-5f4e81f00907/:na]
	at io.cattle.platform.launcher.Main.main(Main.java:251) [0.5.0-SNAPSHOT-44a2a02fbe642620033e4cef2c51554f8e11082e-11f11708-0347-43b4-920b-5f4e81f00907/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at io.cattle.platform.packaging.Bootstrap.run(Bootstrap.java:383) [cattle.jar:0.5.0-SNAPSHOT]
	at io.cattle.platform.packaging.Bootstrap.main(Bootstrap.java:424) [cattle.jar:0.5.0-SNAPSHOT]

04:48:34.668 [main] INFO  ConsoleStatus - [DONE ] [191559ms] Startup Succeeded, Listening on port 8080

**Comment by vincent99** [comment]
The server does not currently support an HTTP proxy and needs to be able to access the internet.  Please watch #90, #129, #135 for progress.
