### ISSUE TITLE
Container stuck in deleting state for hours

### ISSUE THREAD

**Issue by usmanismail** [rancherio/rancher#443]
![screen shot 2015-04-07 at 11 17 36 am](https://cloud.githubusercontent.com/assets/204682/7026495/f9cc2fa2-dd17-11e4-888f-8592e46a8bf9.png)

Container stuck in deleting state for hours, Rancher server logs show the following exception which is possibly related. 

	Exception in API for request [io.github.ibuildthecloud.gdapi.request.ApiRequest@4b80bf68] java.lang.NullPointerException: null
		at io.cattle.platform.iaas.api.auth.github.ProjectResourceManager.listInternal(ProjectResourceManager.java:79) ~[cattle-iaas-auth-logic-0.5.0-SNAPSHOT.jar:na]
		at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.list(AbstractBaseResourceManager.java:82) ~[gdapi-java-server-0.8.0.jar:na]
		at io.github.ibuildthecloud.gdapi.request.resource.impl.AbstractBaseResourceManager.list(AbstractBaseResourceManager.java:73) ~[gdapi-java-server-0.8.0.jar:na]
		at io.github.ibuildthecloud.gdapi.request.handler.ResourceManagerRequestHandler.generate(ResourceManagerRequestHandler.java:53) ~[gdapi-java-server-0.8.0.jar:na]
		at io.github.ibuildthecloud.gdapi.request.handler.AbstractResponseGenerator.handle(AbstractResponseGenerator.java:14) ~[gdapi-java-server-0.8.0.jar:na]
		at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.handle(DefaultReadWriteApiDelegate.java:27) ~[gdapi-java-server-0.8.0.jar:na]
		at io.github.ibuildthecloud.gdapi.request.handler.write.DefaultReadWriteApiDelegate.read(DefaultReadWriteApiDelegate.java:17) ~[gdapi-java-server-0.8.0.jar:na]
		at sun.reflect.GeneratedMethodAccessor640.invoke(Unknown Source) ~[na:na]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
		at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
		at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]
		at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183) ~[spring-aop-3.2.5.RELEASE.jar:3.2.5.RELEASE]

**Comment by ibuildthecloud** [comment]
What is the state of the container on the host?  We see this occasionally when a container gets stuck in a state that can't be deleted.  Can you do a docker ps and see if the container is there?  If it is do a "docker rm -f" and see if it deletes successfully.

**Comment by usmanismail** [comment]
The container is still running. 
I did a docker stop and docker rm -f and the UI is still stuck in deleting phase. 
The container is deleted from the host for sure.

**Comment by deniseschannon** [comment]
@usmanismail Have you seen this issue in the more recent releases (last couple of weeks)? The `--rm` feature wasn't working properly previously. If it's no longer an issue, I'd like to close this issue.

**Comment by usmanismail** [comment]
No I have not.

**Comment by deniseschannon** [comment]
@usmanismail  If you see it again, please feel free to re-open.
