### ISSUE TITLE
NPE when create link for lbService before it was fully created

### ISSUE THREAD

**Issue by alena1108** [rancherio/rancher#702]
We do allow setting service links at any stage of service lifecycle. And if the lb service is not fully created at the moment when links are being set, error happens when consumed services try to register their instances as lb service targets (NPE when try to access LB that wasn't created yet)

2015-05-04 23:24:19,113 ERROR [:] [] [] [] [cutorService-21] [i.c.p.e.e.i.ProcessEventListenerImpl] Unknown exception running process [serviceconsumemap.create:212] on [5] java.lang.NullPointerException: null
	at io.cattle.iaas.lb.service.impl.LoadBalancerServiceImpl.addTargetToLoadBalancer(LoadBalancerServiceImpl.java:91) ~[cattle-iaas-lb-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.servicediscovery.process.ServiceDiscoveryLoadBalancerTargetAddPostListener.handle(ServiceDiscoveryLoadBalancerTargetAddPostListener.java:87) ~[cattle-iaas-service-discovery-server-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:432) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$4.execute(DefaultProcessInstanceImpl.java:372) ~[cattle-framework-engine-0.5.0-SNAPSHOT.jar:na]

**Comment by alena1108** [comment]
@vincent99 the bug you've found

**Comment by vincent99** [comment]
When you create a load balancer service that has service links, the UI sends a post to create the balancer and then immediately after calls the action to set service links.  That's what was failing, so just create a lbservice with links to test.

**Comment by tfiduccia** [comment]
v0.22.0-rc1
Verified fixed
