### ISSUE TITLE
[Install] Stacktrace is thrown when rancher-server is not available

### ISSUE THREAD

**Issue by feliksik** [rancherio/rancher#87]
I use current docker image to start a rancher agent, specifying a ranger server that is not available. Output is a stack trace; this may be a more polished message (like: "giving up" or so). 

By the way, this is a minor issue as the problem is fairly obvious; please let me know whether such reports are appreciated in this phase of the project. 

```
ERROR: http://250.0.100.1:8080 is not accessible
ERROR: http://250.0.100.1:8080 is not accessible
ERROR: http://250.0.100.1:8080 is not accessible
((...) 100 times or so)
ERROR: http://250.0.100.1:8080 is not accessible
ERROR: http://250.0.100.1:8080 is not accessible
ERROR: http://250.0.100.1:8080 is not accessible
Rancher State
Traceback (most recent call last):
  File "./resolve_url.py", line 9, in <module>
    r = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
Traceback (most recent call last):
  File "./register.py", line 8, in <module>
    client = from_env(access_key=os.environ['CATTLE_REGISTRATION_ACCESS_KEY'],
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'CATTLE_REGISTRATION_ACCESS_KEY'

```

**Comment by cloudnautique** [comment]
Thanks @feliksik, we appreciate the feedback. Sorry you ran into this one, we have a fix coming out in the next release of the rancher/agent that addresses the messaging/retry logic.

**Comment by feliksik** [comment]
Thanks, no problem. Looking forward to it!

**Comment by deniseschannon** [comment]
In Version: v0.12.0, the stacktrace is not thrown, instead it shows a message about giving up. 

ERROR: Could not reach http://1.1.1.1:8080. Giving up.
