### ISSUE TITLE
"HTTP Error 503: Service Unavailable" exception by cAdvisor encountered in agent when host agent is behind a proxy.

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#880]
Steps to reproduce the problem:

Cattle Server has public and private ipaddress and is configured with proxy settings.
Host has only  private ipaddress and is configured with proxy settings. 
Host registration for host is done using the private ipaddress  of the cattle server and using proxy settings  -e "http_proxy=http://<ip>:3128"  -e "https_proxy=http://<ip>:3128".

Host gets registered successfully , But following error is seen in the agent logs:
Also I am not able to view the host/container stats.

2015-05-21 21:07:06,729 ERROR cattle [139700678015728] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
time="2015-05-21T21:07:18Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"62c00f9c39e3e7f24f2a7dedf7243c5f863efc2b966b146cf65a8adcfb803697\", From:\"-simulated-\", Time:0}" 
time="2015-05-21T21:08:55Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"b38ef3d2b4ace8544e08e731d689179b51fb5f64371cc39b7195d39aa1c52bee\", From:\"rancher/agent-instance:v0.3.1\", Time:1432242535}" 
time="2015-05-21T21:08:55Z" level="info" msg="Assigning IP [10.42.181.126/16], ContainerId [b38ef3d2b4ace8544e08e731d689179b51fb5f64371cc39b7195d39aa1c52bee], Pid [12976]" 
time="2015-05-21T21:08:55Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"b38ef3d2b4ace8544e08e731d689179b51fb5f64371cc39b7195d39aa1c52bee\", From:\"-simulated-\", Time:0}" 
time="2015-05-21T21:08:55Z" level="info" msg="Container locked. Can't run StartHandler. ID: [b38ef3d2b4ace8544e08e731d689179b51fb5f64371cc39b7195d39aa1c52bee]" 
2015-05-21 21:08:57,558 ERROR cattle [139700678015728] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
2015-05-21 21:08:57,562 ERROR cattle [139700678015728] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
time="2015-05-21T21:08:58Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"1c5de9fa5965ac83afabcff6e18250c6be95367bafba17fdc1c0f054649c267b\", From:\"ubuntu:14.04.2\", Time:1432242538}" 
time="2015-05-21T21:08:59Z" level="info" msg="Assigning IP [10.42.215.207/16], ContainerId [1c5de9fa5965ac83afabcff6e18250c6be95367bafba17fdc1c0f054649c267b], Pid [14205]" 
time="2015-05-21T21:08:59Z" level="info" msg="Processing event: &docker.APIEvents{Status:\"start\", ID:\"1c5de9fa5965ac83afabcff6e18250c6be95367bafba17fdc1c0f054649c267b\", From:\"-simulated-\", Time:0}" 
time="2015-05-21T21:08:59Z" level="info" msg="Container locked. Can't run StartHandler. ID: [1c5de9fa5965ac83afabcff6e18250c6be95367bafba17fdc1c0f054649c267b]" 
2015-05-21 21:13:57,961 ERROR cattle [139700678015728] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable
2015-05-21 21:13:57,969 ERROR cattle [139700678015728] [utils.py:126] Could not get stats from cAdvisor at: http://127.0.0.1:9344/api/v1.2/containers 
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 120, in _get
    with closing(urllib2.urlopen(url, timeout=5)) as resp:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable

**Comment by will-chan** [comment]
Isn't this an issue with not assigning the right host IP when you are registering the agent?

**Comment by ibuildthecloud** [comment]
What environment was this tested on? There was an issue with cadvisor throwing this error on systemd systems, which rhel 7 is one.

**Comment by sangeethah** [comment]
This is seen on ubuntu agents.

**Comment by ibuildthecloud** [comment]
@sangeethah Can you try setting  -e no_proxy=127.0.0.1 on the agent?

**Comment by sangeethah** [comment]
@ibuildthecloud , I tried using "no_proxy=127.0.0.1" when launching agent and I still see this problem:
 
sudo docker run -d --privileged -e "http_proxy=http://test1:***@****:3128" -e "https_proxy=http://test1:***@****:3128” -e  "no_proxy=127.0.0.1" -v /var/run/docker.sock:/var/run/docker.sock rancher/agent:v0.7.9 http://10.132.12.183:8080/v1/scripts/A3ABC9DA656BE68B1993:1433570400000:ZluKVTxstXlllQqB525CDGPbzg

docker inspect shows that "NO_PROXY" is not set ..should I test by setting "NO_PROXY" (all caps) ?

            "CATTLE_AGENT_PIDNS=host",
            "http_proxy=http://test1:sangee123@10.132.41.106:3128",
            "https_proxy=http://test1:sangee123@10.132.41.106:3128",
            "NO_PROXY",
            "CATTLE_PHYSICAL_HOST_UUID",
            "CATTLE_SCRIPT_DEBUG",
            "CATTLE_ACCESS_KEY=1D70517C527A774AA5A7",
            "CATTLE_SECRET_KEY=GvKw4iiPFvMxw9sGLPjmPj9ecmuFnZFCb3ZHYd6Y",
            "CATTLE_AGENT_IP=10.132.12.222",
            "CATTLE_HOST_API_PROXY",
            "CATTLE_SYSTEMD=false",
            "CATTLE_URL=http://10.132.12.183:8080/v1",
            "CATTLE_HOST_LABELS",
            "CATTLE_VOLMGR_ENABLED",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "RANCHER_AGENT_IMAGE=rancher/agent:v0.7.9"

**Comment by sangeethah** [comment]
@ibuildthecloud , I tried using "NO_PROXY=127.0.0.1" when launching agent and this issue is not seen anymore.
