### ISSUE TITLE
Getting an error when registering a host on rancher

### ISSUE THREAD

**Issue by syed** [rancherio/rancher#89]
Hi, 

I am trying to get a dev setup of rancher on my laptop with the cattle running inside eclipse. I am running a VM in virtualbox which I am using as the "host" to create containers in. To register the host, I paste the command something along the lines of 

```bash
docker run --rm -it --privileged -v /var/run/docker.sock:/var/run/docker.sock rancher/agent http://localhost:8080/v1/scripts/384C073484CC9E8F7E53:1423591200000:oshuTaNDDZLSfP5drc5vzk1aCNs
```

However, I get the following error when I view the logs of the container

```
Traceback (most recent call last):
  File "/var/lib/cattle/pyagent/cattle/agent/event.py", line 91, in _worker_main
    resp = agent.execute(req)
  File "/var/lib/cattle/pyagent/cattle/agent/__init__.py", line 15, in execute
    return self._router.route(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_router.py", line 13, in route
    resp = handler.execute(req)
  File "/var/lib/cattle/pyagent/cattle/plugins/core/event_handlers.py", line 32, in execute
    type.on_ping(event, resp)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 54, in on_ping
    self._add_resources(ping, pong)
  File "/var/lib/cattle/pyagent/cattle/plugins/docker/compute.py", line 92, in _add_resources
    'physicalHostStats': self.host_info.collect_data()
  File "/var/lib/cattle/pyagent/cattle/plugins/host_info/main.py", line 17, in collect_data
    data[collector.key_name()] = collector.get_data()
  File "/var/lib/cattle/pyagent/cattle/plugins/host_info/cpu.py", line 76, in get_data
    data.update(self._get_cpu_percentages())
  File "/var/lib/cattle/pyagent/cattle/plugins/host_info/cpu.py", line 47, in _get_cpu_percentages
    stat_prev['timestamp'])
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 96, in timestamp_diff
    time_current_conv = self._timestamp_convert(time_current)
  File "/var/lib/cattle/pyagent/cattle/utils.py", line 105, in _timestamp_convert
    return datetime.strptime(t_strip, "%Y-%m-%dT%H:%M:%S.%f")
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: 208-0
```

Any ideas?

**Comment by cloudnautique** [comment]
This is caused by a bug in the python agent that is being used by the master version of cattle. There is a pull request in python agent (rancherio/python-agent#75) that will fix the issue. To work around until the next iteration of python-agent the simplest workaround would be to set the timezone to UTC.

**Comment by syed** [comment]
Thanks @cloudnautique . It worked!
