### ISSUE TITLE
Not able to use  proxy with authentication enabled where http_proxy is of format "http://<username>:<password>@host:port"

### ISSUE THREAD

**Issue by sangeethah** [rancherio/rancher#937]
Server version - v0.21.1

Steps to reproduce the problem:

Use a proxy which is auth enabled.

set proxy for docker in
/etc/default/docker (set http_proxy parameter to http://<username>:<password>@host:port)  and restart docker.

Install server using the following command:
docker run -d -p 8080:8080 -e "http_proxy=<proxy>" -e "https_proxy=<proxy>" rancher/server:v0.21.1

where proxy is of format = http://<username>:<password>@host:port

When server is installed , all the docker commands are able to use the proxy setting for downloading images needed for server installation.

But the server is not able to load the UI . I do not see the request  - http://releases.rancher.com/ui/0.21.0/static/index.html go to the proxy .

        "Env": [
            "http_proxy=http://test1:***@****:3128",
            "https_proxy=http://test1:****@****:3128",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "DEBIAN_FRONTEND=noninteractive",
            "CATTLE_HOME=/var/lib/cattle",
            "CATTLE_API_UI_INDEX=http://releases.rancher.com/ui/0.21.0/static/index.html",
            "CATTLE_DB_CATTLE_DATABASE=mysql",
            "S6_SERVICE_DIR=/service",
            "RANCHER_SERVER_IMAGE=v0.21.1",
            "CATTLE_MACHINE_EXECUTE=true"
        ],

Exception seen in server logs:
2015-05-27 18:12:11,622 ERROR [:] [] [] [] [main           ] [i.c.p.i.a.s.filter.UIPathFilter     ] Failed to load UI from [http://releases.rancher.com/ui/0.21.0/static/index.html] java.net.UnknownHostException: releases.rancher.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:528) ~[na:1.7.0_79]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.7.0_79]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.7.0_79]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.7.0_79]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.7.0_79]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.7.0_79]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1004) ~[na:1.7.0_79]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:952) ~[na:1.7.0_79]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851) ~[na:1.7.0_79]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301) ~[na:1.7.0_79]
	at io.cattle.platform.iaas.api.servlet.filter.UIPathFilter.reloadIndex(UIPathFilter.java:57) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.servlet.filter.UIPathFilter.init(UIPathFilter.java:35) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:119) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:719) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1252) [jetty-webapp-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:710) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494) [jetty-webapp-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.Server.doStart(Server.java:282) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at io.cattle.platform.launcher.jetty.Main.main(Main.java:125) [0.5.0-SNAPSHOT-d774684e897955d3c941f4123e021fc0920f887e-40ea67fe-c2e4-452f-80ad-3dccecb472c0/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at io.cattle.platform.launcher.Main.run(Main.java:188) [0.5.0-SNAPSHOT-d774684e897955d3c941f4123e021fc0920f887e-40ea67fe-c2e4-452f-80ad-3dccecb472c0/:na]
	at io.cattle.platform.launcher.Main.main(Main.java:251) [0.5.0-SNAPSHOT-d774684e897955d3c941f4123e021fc0920f887e-40ea67fe-c2e4-452f-80ad-3dccecb472c0/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at io.cattle.platform.packaging.Bootstrap.run(Bootstrap.java:383) [cattle.jar:0.5.0-SNAPSHOT]
	at io.cattle.platform.packaging.Bootstrap.main(Bootstrap.java:424) [cattle.jar:0.5.0-SNAPSHOT]

```
1432750048.933    151 10.132.12.221 TCP_MISS/200 3281 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750049.029     87 10.132.12.221 TCP_MISS/200 4447 CONNECT auth.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750053.611   4578 10.132.12.221 TCP_MISS/200 67150 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.016    316 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.026    328 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.029    328 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.030    330 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.031    335 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.032    326 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.034    320 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.037    337 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.039    349 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.041    340 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.050    334 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.053    343 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.056    359 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.056    353 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.065    364 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.072    375 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.076    375 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.086    385 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.087    384 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750054.236    207 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.237    196 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.238    178 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.239    202 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.239    207 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.240    221 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.241    189 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.324    292 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.325    266 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.330    287 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.343    108 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.343    109 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.350    162 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.351    116 10.132.12.221 TCP_MISS/200 6811 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750054.600    365 10.132.12.221 TCP_MISS/200 8610 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750055.034   1333 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750055.037   1331 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750055.060   1357 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750055.074   1364 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750055.077   1365 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750055.128   1427 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750055.296    201 10.132.12.221 TCP_MISS/200 7460 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750055.569    474 10.132.12.221 TCP_MISS/200 7217 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750056.359   2303 10.132.12.221 TCP_MISS/200 1828208 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750056.362   2330 10.132.12.221 TCP_MISS/200 1586940 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750056.380   2345 10.132.12.221 TCP_MISS/200 3102369 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750056.533   2833 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750056.563   2857 10.132.12.221 TCP_MISS/200 4002 CONNECT registry-1.docker.io:443 test1 HIER_DIRECT/162.242.195.84 -
1432750056.934    314 10.132.12.221 TCP_MISS/200 78400 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750057.338   2200 10.132.12.221 TCP_MISS/200 3103189 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750057.693   3652 10.132.12.221 TCP_MISS/200 65908641 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750058.978   2377 10.132.12.221 TCP_MISS/200 1617436 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750060.119   4983 10.132.12.221 TCP_MISS/200 2547143 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750060.569   5377 10.132.12.221 TCP_MISS/200 12874392 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
1432750169.123 114005 10.132.12.221 TCP_MISS/200 110831522 CONNECT dseasb33srnrn.cloudfront.net:443 test1 HIER_DIRECT/54.230.38.52 -
```

**Comment by sangeethah** [comment]
Tested with server version -V0.23.0-rc5

Able to install server successfully in a host with no internet access and which is behind  proxy which is auth enabled.
Docker is set to use this proxy.

Server does not need any proxy settings anymore . releases.rancher.com/ui/0.21.0/static/index.html  is now  packaged with the binaries.
Following command was used to run the server.

docker run -d -p 8080:8080 rancher/server:v0.23.0-rc5
