### ISSUE TITLE
[Install] [Server] I use docker run -d -p 8080:8080 rancher/server, but cannot access 8080 port.

### ISSUE THREAD

**Issue by ahjdzx** [rancherio/rancher#99]
**docker logs** output found ERROR:
```bash
2015-02-13 06:56:01,921 INFO    [main] [ConsoleStatus] [98/98] [14796ms] [0ms] Starting storage-simulator 
2015-02-13 06:58:09,745 ERROR [:] [] [] [] [main           ] [i.c.p.i.a.s.filter.UIPathFilter     ] Failed to load UI from [http://cdn.rancher.io/ui/0.8.5/static/index.html] java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_75]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_75]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_75]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_75]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_75]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_75]
	at java.net.Socket.connect(Socket.java:528) ~[na:1.7.0_75]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.7.0_75]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.7.0_75]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.7.0_75]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.7.0_75]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.7.0_75]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997) ~[na:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933) ~[na:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851) ~[na:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301) ~[na:1.7.0_75]
	at io.cattle.platform.iaas.api.servlet.filter.UIPathFilter.reloadIndex(UIPathFilter.java:57) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at io.cattle.platform.iaas.api.servlet.filter.UIPathFilter.init(UIPathFilter.java:35) [cattle-iaas-api-logic-0.5.0-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:119) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:719) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265) [jetty-servlet-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1252) [jetty-webapp-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:710) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494) [jetty-webapp-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.server.Server.doStart(Server.java:282) [jetty-server-8.1.11.v20130520.jar:8.1.11.v20130520]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.11.v20130520.jar:8.1.11.v20130520]
	at io.cattle.platform.launcher.jetty.Main.main(Main.java:127) [0.5.0-SNAPSHOT-93f331c5190aaf5e606d8b6ba941a04e1c10313c-c7bb7aec-6b02-40a0-80d7-a31a571bde1b/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at io.cattle.platform.launcher.Main.run(Main.java:186) [0.5.0-SNAPSHOT-93f331c5190aaf5e606d8b6ba941a04e1c10313c-c7bb7aec-6b02-40a0-80d7-a31a571bde1b/:na]
	at io.cattle.platform.launcher.Main.main(Main.java:249) [0.5.0-SNAPSHOT-93f331c5190aaf5e606d8b6ba941a04e1c10313c-c7bb7aec-6b02-40a0-80d7-a31a571bde1b/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_75]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_75]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_75]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_75]
	at io.cattle.platform.packaging.Bootstrap.run(Bootstrap.java:386) [cattle.jar:0.5.0-SNAPSHOT]
	at io.cattle.platform.packaging.Bootstrap.main(Bootstrap.java:426) [cattle.jar:0.5.0-SNAPSHOT]

06:58:09.763 [main] INFO  ConsoleStatus - [DONE ] [145808ms] Startup Succeeded, Listening on port 8080
```

**Comment by vincent99** [comment]
Is the machine you're running rancher/server on blocked from outbound access to the internet?  The UI is hosted on cdn.rancher.io and the HTML that is served up is pulled in by the server.  Your stack trace indicates that it was unable to do so:

```
Failed to load UI from [http://cdn.rancher.io/ui/0.8.5/static/index.html]
java.net.ConnectException: Connection timed out
```

**Comment by deniseschannon** [comment]
@ahjdzx If you are still running into this issue, please re-open. It looks as if @vincent99 has addressed what might be the problem.
